services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mitienda
      POSTGRES_PASSWORD: mitienda
      POSTGRES_DB: mitienda
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  backend:
    build: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://mitienda:mitienda@db:5432/mitienda
      SECRET_KEY: e8b8f4d9a8b8c8d8e8f8g8h8i8j8k8l8m8n8o8p8q8r8s8t8u8v8w8x8y8z8a8b8
      PROJECT_NAME: "MiTienda API"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elastic

  frontend:
    build: ../frontend
    command: pnpm dev --host
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:
