import type { Product, Category, HeroSlide } from '@/lib/types';
import { getImage } from '@/lib/placeholder-images';

export const categories: Category[] = [
  { id: '1', name: "Mujer", slug: 'mujer', imageUrl: getImage('cat1').imageUrl, imageHint: getImage('cat1').imageHint },
  { id: '2', name: 'Hogar y Cocina', slug: 'hogar-cocina', imageUrl: getImage('cat2').imageUrl, imageHint: getImage('cat2').imageHint },
  { id: '3', name: 'Electrónicos', slug: 'electronicos', imageUrl: getImage('cat3').imageUrl, imageHint: getImage('cat3').imageHint },
  { id: '4', name: 'Juguetes y Juegos', slug: 'juguetes-juegos', imageUrl: getImage('cat4').imageUrl, imageHint: getImage('cat4').imageHint },
  { id: '5', name: 'Belleza', slug: 'belleza', imageUrl: getImage('cat5').imageUrl, imageHint: getImage('cat5').imageHint },
  { id: '6', name: 'Deportes', slug: 'deportes', imageUrl: getImage('cat6').imageUrl, imageHint: getImage('cat6').imageHint },
  { id: '7', name: 'Hombre', slug: 'hombre', imageUrl: getImage('cat1').imageUrl, imageHint: getImage('cat1').imageHint },
  { id: '8', name: 'Automóviles', slug: 'automoviles', imageUrl: getImage('cat2').imageUrl, imageHint: getImage('cat2').imageHint },
  { id: '9', name: 'Libros y Medios', slug: 'libros-medios', imageUrl: getImage('cat3').imageUrl, imageHint: getImage('cat3').imageHint },
  { id: '10', name: 'Salud y Bienestar', slug: 'salud-bienestar', imageUrl: getImage('cat4').imageUrl, imageHint: getImage('cat4').imageHint },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'futuristic-smart-watch',
    title: 'Reloj Inteligente Futurista',
    description: 'Un reloj inteligente elegante y moderno con todas las últimas características.',
    price: 199.99,
    compareAtPrice: 249.99,
    category: 'electronicos',
    rating: 4.5,
    reviews: 120,
    imageUrl: getImage('prod1').imageUrl,
    imageHint: getImage('prod1').imageHint
  },
  {
    id: '2',
    slug: 'noise-cancelling-headphones',
    title: 'Audífonos con Cancelación de Ruido',
    description: 'Sumérgete en el sonido con estos audífonos de alta calidad.',
    price: 149.50,
    category: 'electronicos',
    rating: 4.8,
    reviews: 250,
    imageUrl: getImage('prod2').imageUrl,
    imageHint: getImage('prod2').imageHint
  },
  {
    id: '3',
    slug: 'high-speed-kitchen-blender',
    title: 'Licuadora de Cocina de Alta Velocidad',
    description: 'Perfecta para batidos, sopas y más. Un elemento esencial de la cocina.',
    price: 89.99,
    compareAtPrice: 119.99,
    category: 'hogar-cocina',
    rating: 4.7,
    reviews: 95,
    imageUrl: getImage('prod3').imageUrl,
    imageHint: getImage('prod3').imageHint
  },
  {
    id: '4',
    slug: 'lightweight-running-shoes',
    title: 'Zapatos Deportivos Ligeros',
    description: 'Experimenta comodidad y rendimiento en tu carrera diaria.',
    price: 120.00,
    category: 'deportes',
    rating: 4.6,
    reviews: 180,
    imageUrl: getImage('prod4').imageUrl,
    imageHint: getImage('prod4').imageHint
  },
  {
    id: '5',
    slug: 'organic-skincare-set',
    title: 'Conjunto de Cuidado de la Piel Orgánico',
    description: 'Rejuvenece tu piel con este conjunto de cuidado completamente natural.',
    price: 75.00,
    category: 'belleza',
    rating: 4.9,
    reviews: 310,
    imageUrl: getImage('prod5').imageUrl,
    imageHint: getImage('prod5').imageHint
  },
  {
    id: '6',
    slug: 'pro-yoga-mat',
    title: 'Tapete de Yoga Profesional',
    description: 'Tapete antideslizante y ecológico para tu práctica de yoga.',
    price: 45.00,
    compareAtPrice: 59.99,
    category: 'deportes',
    rating: 4.7,
    reviews: 150,
    imageUrl: getImage('prod6').imageUrl,
    imageHint: getImage('prod6').imageHint
  },
  {
    id: '7',
    slug: '4k-camera-drone',
    title: 'Dron con Cámara 4K',
    description: 'Captura vistas aéreas impresionantes con este dron fácil de volar.',
    price: 499.00,
    category: 'electronicos',
    rating: 4.8,
    reviews: 78,
    imageUrl: getImage('prod7').imageUrl,
    imageHint: getImage('prod7').imageHint
  },
  {
    id: '8',
    slug: 'vintage-leather-backpack',
    title: 'Mochila de Cuero Vintage',
    description: 'Mochila elegante y duradera para trabajo o viajes.',
    price: 110.00,
    category: 'mujer',
    rating: 4.5,
    reviews: 99,
    imageUrl: getImage('prod8').imageUrl,
    imageHint: getImage('prod8').imageHint
  },
   {
    id: '9',
    slug: 'led-desk-lamp',
    title: 'Lámpara de Escritorio LED',
    description: 'Lámpara de escritorio moderna y ajustable con múltiples niveles de brillo.',
    price: 39.99,
    category: 'hogar-cocina',
    rating: 4.6,
    reviews: 210,
    imageUrl: getImage('prod9').imageUrl,
    imageHint: getImage('prod9').imageHint
  },
  {
    id: '10',
    slug: 'ergonomic-gaming-mouse',
    title: 'Ratón Gaming Ergonómico',
    description: 'Ratón gaming de alta precisión para el jugador competitivo.',
    price: 65.00,
    compareAtPrice: 85.00,
    category: 'electronicos',
    rating: 4.8,
    reviews: 450,
    imageUrl: getImage('prod10').imageUrl,
    imageHint: getImage('prod10').imageHint
  },
  {
    id: '11',
    slug: 'automatic-drip-coffee-maker',
    title: 'Cafetera de Goteo Automática',
    description: 'Prepara la taza de café perfecta cada mañana.',
    price: 55.50,
    category: 'hogar-cocina',
    rating: 4.5,
    reviews: 130,
    imageUrl: getImage('prod11').imageUrl,
    imageHint: getImage('prod11').imageHint
  },
  {
    id: '12',
    slug: 'classic-aviator-sunglasses',
    title: 'Gafas de Sol Aviador Clásicas',
    description: 'Estilo atemporal con protección UV.',
    price: 25.00,
    category: 'mujer',
    rating: 4.4,
    reviews: 500,
    imageUrl: getImage('prod12').imageUrl,
    imageHint: getImage('prod12').imageHint
  },
  {
    id: '13',
    slug: 'portable-bluetooth-speaker',
    title: 'Altavoz Bluetooth Portátil',
    description: 'Altavoz compacto con sonido potente y batería de larga duración.',
    price: 49.99,
    category: 'electronicos',
    rating: 4.7,
    reviews: 320,
    imageUrl: getImage('prod13').imageUrl,
    imageHint: getImage('prod13').imageHint
  },
  {
    id: '14',
    slug: 'electric-toothbrush',
    title: 'Cepillo de Dientes Eléctrico',
    description: 'Tecnología de limpieza avanzada para una sonrisa más saludable.',
    price: 79.99,
    category: 'belleza',
    rating: 4.9,
    reviews: 180,
    imageUrl: getImage('prod14').imageUrl,
    imageHint: getImage('prod14').imageHint
  },
  {
    id: '15',
    slug: 'insulated-stainless-steel-water-bottle',
    title: 'Botella de Agua Aislada',
    description: 'Mantiene las bebidas frías por 24 horas o calientes por 12 horas.',
    price: 29.95,
    category: 'deportes',
    rating: 4.8,
    reviews: 600,
    imageUrl: getImage('prod15').imageUrl,
    imageHint: getImage('prod15').imageHint
  },
  {
    id: '16',
    slug: 'bestselling-mystery-novel',
    title: 'Novela de Misterio Más Vendida',
    description: 'Una emocionante historia de suspenso que no podrás soltar.',
    price: 14.99,
    category: 'juguetes-juegos',
    rating: 4.6,
    reviews: 1250,
    imageUrl: getImage('prod16').imageUrl,
    imageHint: getImage('prod16').imageHint
  },
  {
    id: '17',
    slug: 'wireless-charging-pad',
    title: 'Almohadilla de Carga Inalámbrica',
    description: 'Cargador inalámbrico rápido y compatible con todos los dispositivos.',
    price: 35.99,
    category: 'electronicos',
    rating: 4.7,
    reviews: 380,
    imageUrl: getImage('prod1').imageUrl,
    imageHint: getImage('prod1').imageHint
  },
  {
    id: '18',
    slug: 'memory-foam-pillow',
    title: 'Almohada de Espuma Viscoelástica',
    description: 'Almohada ortopédica para un descanso confortable y saludable.',
    price: 45.00,
    compareAtPrice: 65.00,
    category: 'hogar-cocina',
    rating: 4.8,
    reviews: 520,
    imageUrl: getImage('prod2').imageUrl,
    imageHint: getImage('prod2').imageHint
  },
  {
    id: '19',
    slug: 'sports-backpack',
    title: 'Mochila Deportiva Premium',
    description: 'Mochila resistente y cómoda para deportes y viajes.',
    price: 89.99,
    category: 'deportes',
    rating: 4.6,
    reviews: 290,
    imageUrl: getImage('prod3').imageUrl,
    imageHint: getImage('prod3').imageHint
  },
  {
    id: '20',
    slug: 'beauty-face-mask',
    title: 'Mascarilla Facial Hidratante',
    description: 'Mascarilla de lujo con ingredientes naturales para piel radiante.',
    price: 22.50,
    category: 'belleza',
    rating: 4.9,
    reviews: 650,
    imageUrl: getImage('prod4').imageUrl,
    imageHint: getImage('prod4').imageHint
  },
  {
    id: '21',
    slug: 'smartwatch-fitness',
    title: 'Reloj Inteligente Fitness',
    description: 'Monitor de salud completo con seguimiento de pasos y calorías.',
    price: 149.99,
    compareAtPrice: 199.99,
    category: 'electronicos',
    rating: 4.8,
    reviews: 410,
    imageUrl: getImage('prod5').imageUrl,
    imageHint: getImage('prod5').imageHint
  },
  {
    id: '22',
    slug: 'kitchen-knife-set',
    title: 'Juego de Cuchillos de Cocina',
    description: 'Set profesional de cuchillos de acero inoxidable.',
    price: 69.99,
    category: 'hogar-cocina',
    rating: 4.7,
    reviews: 340,
    imageUrl: getImage('prod6').imageUrl,
    imageHint: getImage('prod6').imageHint
  },
  {
    id: '23',
    slug: 'winter-jacket-women',
    title: 'Chaqueta de Invierno para Mujer',
    description: 'Chaqueta cálida y moderna con aislamiento térmico.',
    price: 129.99,
    category: 'mujer',
    rating: 4.6,
    reviews: 280,
    imageUrl: getImage('prod7').imageUrl,
    imageHint: getImage('prod7').imageHint
  },
  {
    id: '24',
    slug: 'gaming-monitor-4k',
    title: 'Monitor Gaming 4K',
    description: 'Monitor de 4K con tasa de refresco de 144Hz para gaming.',
    price: 399.99,
    compareAtPrice: 499.99,
    category: 'electronicos',
    rating: 4.9,
    reviews: 195,
    imageUrl: getImage('prod8').imageUrl,
    imageHint: getImage('prod8').imageHint
  },
  {
    id: '25',
    slug: 'yoga-mat-premium',
    title: 'Tapete de Yoga Premium',
    description: 'Tapete grueso y resistente para yoga y pilates.',
    price: 55.00,
    category: 'deportes',
    rating: 4.8,
    reviews: 420,
    imageUrl: getImage('prod9').imageUrl,
    imageHint: getImage('prod9').imageHint
  },
  {
    id: '26',
    slug: 'wireless-earbuds',
    title: 'Auriculares Inalámbricos',
    description: 'Auriculares TWS con cancelación de ruido activa.',
    price: 99.99,
    compareAtPrice: 139.99,
    category: 'electronicos',
    rating: 4.8,
    reviews: 610,
    imageUrl: getImage('prod10').imageUrl,
    imageHint: getImage('prod10').imageHint
  },
  {
    id: '27',
    slug: 'leather-belt',
    title: 'Cinturón de Cuero Genuino',
    description: 'Cinturón de cuero de alta calidad para hombre.',
    price: 35.50,
    category: 'hombre',
    rating: 4.5,
    reviews: 185,
    imageUrl: getImage('prod11').imageUrl,
    imageHint: getImage('prod11').imageHint
  },
  {
    id: '28',
    slug: 'coffee-maker-espresso',
    title: 'Cafetera Espresso Manual',
    description: 'Cafetera de espresso manual de acero inoxidable.',
    price: 85.99,
    category: 'hogar-cocina',
    rating: 4.7,
    reviews: 260,
    imageUrl: getImage('prod12').imageUrl,
    imageHint: getImage('prod12').imageHint
  },
  {
    id: '29',
    slug: 'portable-projector',
    title: 'Proyector Portátil',
    description: 'Proyector LED portátil con conexión inalámbrica.',
    price: 199.99,
    category: 'electronicos',
    rating: 4.6,
    reviews: 145,
    imageUrl: getImage('prod13').imageUrl,
    imageHint: getImage('prod13').imageHint
  },
  {
    id: '30',
    slug: 'hair-dryer-ionic',
    title: 'Secador de Cabello Iónico',
    description: 'Secador profesional con tecnología iónica.',
    price: 65.99,
    compareAtPrice: 85.00,
    category: 'belleza',
    rating: 4.8,
    reviews: 380,
    imageUrl: getImage('prod14').imageUrl,
    imageHint: getImage('prod14').imageHint
  },
  {
    id: '31',
    slug: 'running-shoes-men',
    title: 'Zapatos para Correr Hombre',
    description: 'Zapatillas deportivas ligeras y cómodas para correr.',
    price: 110.00,
    category: 'deportes',
    rating: 4.7,
    reviews: 510,
    imageUrl: getImage('prod15').imageUrl,
    imageHint: getImage('prod15').imageHint
  },
  {
    id: '32',
    slug: 'desk-organizer',
    title: 'Organizador de Escritorio',
    description: 'Organizador modular para mantener tu escritorio limpio.',
    price: 28.99,
    category: 'hogar-cocina',
    rating: 4.6,
    reviews: 220,
    imageUrl: getImage('prod1').imageUrl,
    imageHint: getImage('prod1').imageHint
  },
  {
    id: '33',
    slug: 'bluetooth-speaker-outdoor',
    title: 'Altavoz Bluetooth Resistente al Agua',
    description: 'Altavoz portátil con impermeabilización IP67.',
    price: 79.99,
    category: 'electronicos',
    rating: 4.8,
    reviews: 445,
    imageUrl: getImage('prod2').imageUrl,
    imageHint: getImage('prod2').imageHint
  },
  {
    id: '34',
    slug: 'womens-dress',
    title: 'Vestido Casual de Mujer',
    description: 'Vestido elegante y cómodo para usar en cualquier ocasión.',
    price: 75.00,
    category: 'mujer',
    rating: 4.5,
    reviews: 315,
    imageUrl: getImage('prod3').imageUrl,
    imageHint: getImage('prod3').imageHint
  },
  {
    id: '35',
    slug: 'smart-home-light-bulb',
    title: 'Bombilla Inteligente LED',
    description: 'Bombilla inteligente controlable por voz con cambio de color.',
    price: 25.99,
    category: 'hogar-cocina',
    rating: 4.7,
    reviews: 380,
    imageUrl: getImage('prod4').imageUrl,
    imageHint: getImage('prod4').imageHint
  },
  {
    id: '36',
    slug: 'action-camera',
    title: 'Cámara de Acción 4K',
    description: 'Cámara deportiva 4K resistente al agua.',
    price: 249.99,
    compareAtPrice: 299.99,
    category: 'electronicos',
    rating: 4.8,
    reviews: 290,
    imageUrl: getImage('prod5').imageUrl,
    imageHint: getImage('prod5').imageHint
  },
  {
    id: '37',
    slug: 'fitness-tracker',
    title: 'Pulsera de Actividad Fitness',
    description: 'Pulsera inteligente para monitorear tu actividad física.',
    price: 89.99,
    category: 'deportes',
    rating: 4.6,
    reviews: 425,
    imageUrl: getImage('prod6').imageUrl,
    imageHint: getImage('prod6').imageHint
  },
  {
    id: '38',
    slug: 'vintage-camera',
    title: 'Cámara Vintage Analógica',
    description: 'Cámara analógica clásica de los 80s restaurada.',
    price: 159.99,
    category: 'electronicos',
    rating: 4.5,
    reviews: 135,
    imageUrl: getImage('prod7').imageUrl,
    imageHint: getImage('prod7').imageHint
  },
  {
    id: '39',
    slug: 'reading-glasses',
    title: 'Gafas de Lectura',
    description: 'Gafas de lectura premium con lentes anti-reflectantes.',
    price: 35.00,
    category: 'belleza',
    rating: 4.4,
    reviews: 198,
    imageUrl: getImage('prod8').imageUrl,
    imageHint: getImage('prod8').imageHint
  },
  {
    id: '40',
    slug: 'tent-camping',
    title: 'Tienda de Campaña 4 Personas',
    description: 'Tienda de campaña de calidad con protección UV.',
    price: 199.99,
    compareAtPrice: 249.99,
    category: 'deportes',
    rating: 4.7,
    reviews: 285,
    imageUrl: getImage('prod9').imageUrl,
    imageHint: getImage('prod9').imageHint
  },
  {
    id: '41',
    slug: 'usb-hub-multiport',
    title: 'Hub USB Multipuerto',
    description: 'Hub USB 3.0 de 7 puertos con fuente de alimentación.',
    price: 39.99,
    category: 'electronicos',
    rating: 4.6,
    reviews: 275,
    imageUrl: getImage('prod10').imageUrl,
    imageHint: getImage('prod10').imageHint
  },
  {
    id: '42',
    slug: 'skateboard-professional',
    title: 'Patineta Profesional',
    description: 'Patineta de madera de arce de alta calidad.',
    price: 95.00,
    category: 'deportes',
    rating: 4.7,
    reviews: 365,
    imageUrl: getImage('prod11').imageUrl,
    imageHint: getImage('prod11').imageHint
  },
  {
    id: '43',
    slug: 'leather-shoes-mens',
    title: 'Zapatos de Cuero para Hombre',
    description: 'Zapatos de cuero genuino elegantes y cómodos.',
    price: 125.00,
    compareAtPrice: 165.00,
    category: 'hombre',
    rating: 4.6,
    reviews: 420,
    imageUrl: getImage('prod12').imageUrl,
    imageHint: getImage('prod12').imageHint
  },
  {
    id: '44',
    slug: 'microwave-oven',
    title: 'Microondas Inteligente',
    description: 'Microondas con control digital y sensor automático.',
    price: 159.99,
    category: 'hogar-cocina',
    rating: 4.7,
    reviews: 310,
    imageUrl: getImage('prod13').imageUrl,
    imageHint: getImage('prod13').imageHint
  },
  {
    id: '45',
    slug: 'desk-lamp-led',
    title: 'Lámpara LED de Escritorio Regulable',
    description: 'Lámpara LED con 5 modos de brillo y color.',
    price: 45.99,
    category: 'hogar-cocina',
    rating: 4.8,
    reviews: 395,
    imageUrl: getImage('prod14').imageUrl,
    imageHint: getImage('prod14').imageHint
  },
  {
    id: '46',
    slug: 'moisturizer-cream',
    title: 'Crema Hidratante Premium',
    description: 'Crema hidratante facial de lujo con ácido hialurónico.',
    price: 42.00,
    category: 'belleza',
    rating: 4.9,
    reviews: 580,
    imageUrl: getImage('prod15').imageUrl,
    imageHint: getImage('prod15').imageHint
  },
  {
    id: '47',
    slug: 'gaming-chair',
    title: 'Silla Gaming Ergonómica',
    description: 'Silla gaming con soporte lumbar y reposabrazos ajustables.',
    price: 259.99,
    compareAtPrice: 349.99,
    category: 'hogar-cocina',
    rating: 4.8,
    reviews: 520,
    imageUrl: getImage('prod1').imageUrl,
    imageHint: getImage('prod1').imageHint
  },
  {
    id: '48',
    slug: 'wireless-mouse-keyboard',
    title: 'Combo Teclado y Ratón Inalámbrico',
    description: 'Teclado y ratón inalámbricos con batería larga duración.',
    price: 69.99,
    category: 'electronicos',
    rating: 4.7,
    reviews: 340,
    imageUrl: getImage('prod2').imageUrl,
    imageHint: getImage('prod2').imageHint
  },
  {
    id: '49',
    slug: 'plant-pot-ceramic',
    title: 'Maceta de Cerámica',
    description: 'Maceta decorativa de cerámica con plato.',
    price: 24.99,
    category: 'hogar-cocina',
    rating: 4.5,
    reviews: 155,
    imageUrl: getImage('prod3').imageUrl,
    imageHint: getImage('prod3').imageHint
  },
  {
    id: '50',
    slug: 'watch-luxury',
    title: 'Reloj de Lujo Analógico',
    description: 'Reloj de cuarzo de lujo con correa de cuero genuine.',
    price: 189.99,
    category: 'hombre',
    rating: 4.8,
    reviews: 410,
    imageUrl: getImage('prod4').imageUrl,
    imageHint: getImage('prod4').imageHint
  },
];

export const heroSlides: HeroSlide[] = [
    {
        id: 1,
        title: "Ofertas Relámpago, Precios Imbatibles",
        subtitle: "Descubre ahorros increíbles en miles de artículos. ¡Ofertas limitadas diariamente!",
        alt: "Venta emocionante de moda",
        link: "/deals",
        cta: "Comprar Ahora",
        imageUrl: getImage('hero1').imageUrl,
        imageHint: getImage('hero1').imageHint
    },
    {
        id: 2,
        title: "Actualiza tu Tecnología",
        subtitle: "Los últimos gadgets y electrónica están a solo un clic de distancia. Envío gratis en órdenes superiores a $50.",
        alt: "Colección de gadgets electrónicos modernos",
        link: "/category/electronicos",
        cta: "Explorar Electrónicos",
        imageUrl: getImage('hero2').imageUrl,
        imageHint: getImage('hero2').imageHint
    },
    {
        id: 3,
        title: "Transforma tu Hogar",
        subtitle: "Encuentra decoración única y elegante para renovar tu espacio.",
        alt: "Sala de estar bellamente decorada",
        link: "/category/hogar-cocina",
        cta: "Descubrir Hogar",
        imageUrl: getImage('hero3').imageUrl,
        imageHint: getImage('hero3').imageHint
    }
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find((p) => p.slug === slug);
};
